Core data
BritneyS/GetFed pull request #23
Opened 2018-12-11 18:55 UTC by BritneyS

## What you did :question:
- Added Core Data functionality so that custom user food entries are saved in Core Data's SQLite database
- Added alerts for both successful and failing saves

## How you did it :white_check_mark:
- Created managedContext object to hold values for Core Data Entities
- Saved the entries for the fields in the Food Entry view to the appropriate entities, Food and Nutrients, and linked the entities (one-to-one relationship); method is called upon tapping 'Save'
- Wrote method to clear textfields upon successful save
- Wrote methods to call alerts for successful and failed saves
- Added temporary method `readRecords()` to display all current records in the data store (to test the save feature)

## How to test it :microscope:
- Run the app
- Tap 'Food Entry'
- Enter values in the Food Entry's fields
- Tap 'Save'
- Note that a success alert message is displayed, and the message includes the name of the food entry
- Note that in the Terminal, the values of the new food entry (starts with 🍞) and the current contents of the data store (starts with 🍎) are displayed. The new food entry should appear at the end of the 🍎list

## Screenshots (if applicable) :camera:
![simulator screen shot - iphone xr - 2018-12-11 at 11 18 09](https://user-images.githubusercontent.com/8409475/49822613-9a6cdb80-fd4b-11e8-957e-125dfeb1841e.png)
![simulator screen shot - iphone xr - 2018-12-11 at 11 18 17](https://user-images.githubusercontent.com/8409475/49822619-a3f64380-fd4b-11e8-9291-9e1615557bdd.png)
![simulator screen shot - iphone xr - 2018-12-11 at 11 18 23](https://user-images.githubusercontent.com/8409475/49822661-be302180-fd4b-11e8-91f1-6e2ab9697983.png)
![screen shot 2018-12-11 at 1 53 00 pm](https://user-images.githubusercontent.com/8409475/49822806-267f0300-fd4c-11e8-967c-22a17186dcd7.png)

2018-12-11 20:05 UTC, jshier requested changes
I think separating the Core Data and networking types would be beneficial, as well as separating the Core Data stuff from the `UIApplication`.

2018-12-11 20:05 UTC, jshier commented on GetFed/GetFed/Controllers/FoodEntryViewController.swift
> +        return appDelegate.persistentContainer.viewContext
It's not a good idea to attach any functionality to your app delegate. Your context should stand alone, likely as a separate singleton or controller that interested parties talk to fetch and store data.

2018-12-11 20:05 UTC, jshier commented on GetFed/GetFed/Models/Food.swift
> +@objc(Food)
It may not be a good idea to combine your `Codable` implementations with your Core Data implementations, as they're really two different things and you may make both more complex if they're combined. For instance, I'm pretty sure `NSManagedObject`s are supposed to be able to encode and decode themselves automatically without having to implement this, or care what context the value is coming from.

2018-12-11 20:05 UTC, jshier commented on GetFed/GetFed/Models/Food.swift
> +@objc(Food)
It might be a good idea to have one type you use for network calls and another you store locally, each with their own definitions and perhaps a way to translate between the two. But I think combining them is giving the poorer representations for both.

2018-12-12 19:27 UTC, BritneyS commented on GetFed/GetFed/Controllers/FoodEntryViewController.swift
> +        return appDelegate.persistentContainer.viewContext
@jshier I've pushed up changes to improve on this. Last commit is be3980a.

Edit: last commit is now a895059, but it's just removing a comment.

2018-12-13 14:35 UTC, BritneyS commented on GetFed/GetFed/Models/Food.swift
> +@objc(Food)
@jshier That makes sense. 

It seems appropriate to merge this branch now, then decouple the networking and Core Data models on another branch.

2018-12-13 14:36 UTC, BritneyS commented
Merging this, but still open to review!

2018-12-13 14:36 UTC, merged